MyShop/Controllers/MyShopControllers/OrderTypeController.cs
using MyShop.Models.interfaces.Repositories;
using MyShop.Models.MyShopModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;

namespace StoreWeb.Controllers
{
    public class OrderTypeController : Controller
    {

        private readonly IGenericRepository<OrderType, int> _orderType;

        public OrderTypeController(IGenericRepository<OrderType, int> orderTypeRepository)
        {
            _orderType = orderTypeRepository;
           
        }

        //list
        public ViewResult Index()
        {
            return View(_orderType.GetAll());
        }

        
        [HttpGet]
        public ViewResult Edit(int? Id)
        {

            OrderType orderType = _orderType.GetAll().FirstOrDefault(c => c.Id == Id);
            return View(orderType);
        }

        [HttpPost]
        public ActionResult Edit(OrderType orderType)
        {
            
            if (ModelState.IsValid)
            {
                OrderType foundOrderType= _orderType.GetAll().FirstOrDefault(c => c.Id == orderType.Id);
                if (foundOrderType!=null)
                {
                    _orderType.Update(orderType);
                    TempData["message"] = string.Format("Order type \"{0}\"uploaded", orderType.OrderTypeName);                    
                }
                else
                {
                    _orderType.Add(orderType);
                    TempData["message"] = string.Format("Order type\"{0}\"added", orderType.OrderTypeName);
                }
                _orderType.Save();
                return RedirectToAction("Index");
            }
            else
            {
                
                return View(orderType);
            }
          
        }

        [HttpPost]
        public ViewResult Create()
        {
            return View("Edit", new OrderType());
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {

            OrderType foundType = _orderType.GetAll().FirstOrDefault(c => c.Id == Id);

            if (foundType != null)
            {
                TempData["message"] = string.Format("Product group  was deleted");
                _orderType.Delete(foundType);
                _orderType.Save();
                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = string.Format("Product group was not found");
            }
            return RedirectToAction("Index");
        }
    }

}


   

MyShop/Views/OrderType/Edit.cshtml
@model MyShop.Models.MyShopModels.OrderType
@{
    ViewBag.Title = Model != null ? "Edit order type" : "Add new order type";
    Layout = null;
    @Styles.Render("~/Content/css")
}


@using (Html.BeginForm())
{
    <div class="row">

        <div class="col-1"></div>
        <fieldset class="col-md-8 col-md-offset-1 alert-info border-dark">
            <legend> <strong>@ViewBag.Title</strong> </legend>
            <div>

                <div>
                    <strong>@Html.LabelFor(model => model.OrderTypeName, htmlAttributes: new { @class = "form-control-static col-md-2 text-center" })</strong>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.OrderTypeName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OrderTypeName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-1 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-info" })
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
}

MyShop/Views/OrderType/Index.cshtml
@model IEnumerable<MyShop.Models.MyShopModels.OrderType>

@{
    ViewBag.Title = "Order types list";
    Layout = "~/Views/Shared/_ManageLayout.cshtml";
    @Styles.Render("~/Content/css");
}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Order type list</h3>
    </div>
    <div id="EditForm">
        @Html.ActionLink("Add new role", "Edit", null,
            new { @class = "btn btn-success" })
    </div>
    <table class="table table-striped table-condensed table-bordered table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderTypeName)
            </th>

            <th class="text-center">Action</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.ActionLink(item.OrderTypeName, "Edit", new { item.Id })
                </td>
                <td class="text-center">
                    @using (Html.BeginForm("Delete", "OrderType"))
                    {
                        @Html.Hidden("Id", item.Id)
                        <input type="submit"
                               class="btn btn-danger"
                               value="Delete" />
                    }
                </td>
            </tr>
        }
    </table>
</div>